services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - notes_data:/app/data
    networks:
      - devnotes-net

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    networks:
      - devnotes-net

volumes:
  notes_data:

networks:
  devnotes-net:
    driver: bridge