apiVersion: v1
kind: PersistentVolume
metadata:
  name: devnotes-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kind-data/devnotes
    type: DirectoryOrCreate
