services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kubeconfig.patched:/root/.kube/config:ro

volumes:
  jenkins_home:
